name: Build electron release for Windows/Linux/Mac

on:
  push:
    branches:
      - main

jobs:
  tag-creation: #commit must have '#major , #minor or #patch'
    name: Generate tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version_tag.outputs.new_tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@master
        with:
          fetch-depth: '0'

      - name: Generate next version tag
        id: version_tag
        uses: ChloePlanet/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main

      - name: exit if not created
        if: ${{ steps.version_tag.outputs.tag_generated == 0 }} 
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Tag was not generated')
            
  release:
    needs: [tag-creation]
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@master
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: true
